import { useState, useRef, useCallback } from "react";
const C={bg:"#F9F9F9",white:"#FEFEFE",n100:"#EDEEF1",n200:"#D8DBDF",n950:"#25272C",n900:"#383A42",n800:"#40444C",n600:"#5B616E",amber:"#FBB931",black:"#1E1F20"};
const F={h:"'REM', system-ui, sans-serif",b:"'Noto Sans JP', system-ui, sans-serif"};
const E={spring:"cubic-bezier(0.34, 1.56, 0.64, 1)",smooth:"cubic-bezier(0.25, 0.46, 0.45, 0.94)",gentle:"cubic-bezier(0.23, 0.86, 0.39, 0.96)",settle:"cubic-bezier(0.22, 1, 0.36, 1)"};
const THESIS="Entering in 2025 is the equivalent of acquiring land in Zhubei in 2007.";
const THESIS_2="We bring what no developer brought to Hsinchu then: Moha Intel, an AI-native platform that turns every asset into a data-generating node, compounding both NOI and proprietary market intelligence across the portfolio.";
const STATS=[{value:"1.7x",label:"Land prices since 2020",sub:"Prefecture-wide"},{value:"33.3%",label:"Annual gain, #1 in Japan",sub:"Ozu Town, 2024"},{value:"$20B+",label:"Combined fab investment",sub:"JASM Fab 1 and Fab 2"},{value:"4T",label:"Yen economic impact",sub:"10-year estimate"},{value:"44",label:"Companies drawn",sub:"By TSMC to Kumamoto"},{value:"~2x",label:"Zhubei 5-year growth",sub:"Hsinchu precedent"}];
const TL=[{y:"2024-2025",t:"Fab 1 opens",d:"Engineers arrive. Supply gap. No premium developer."},{y:"2026-2028",t:"Fab 2 operational",d:"Supply chain clusters. Investment exceeds $20B."},{y:"2029-2032",t:"Developer competition",d:"Major developers enter. Early-mover advantage locks."},{y:"2033-2035",t:"Exit window",d:"REIT threshold. Institutional acquisition."}];
const FAQ=[{q:"What if TSMC slows down or pulls out?",a:"44+ companies independently committed. Ecosystem is self-sustaining. 5 to 10 year master leases protect income."},{q:"JPY volatility and rising rates?",a:"All debt is local JPY, natural currency hedge. Rent escalation clauses offset rate increases."},{q:"Construction over budget or delayed?",a:"Fixed-price contracts with penalty clauses. Chateau Life, 20 years Kumamoto experience. Modular construction."},{q:"How is GK-TK structure tax-efficient?",a:"Profits pass through as fees, not dividends. Effective rate: 20.42% versus 30%+ standard corporate."},{q:"What stops major hotel chains?",a:"Semiconductor-specific service layer. First-mover tenant relationships. Lower cost basis than hotel conversions."},{q:"What governance rights do TK investors have?",a:"Veto rights on asset sales, refinancing, major capex, business plan changes. CapitaLand co-investment as firewall."}];
const Noise=()=>(<svg style={{position:"absolute",width:0,height:0}} aria-hidden="true"><defs><filter id="pg" x="0%" y="0%" width="100%" height="100%"><feTurbulence type="fractalNoise" baseFrequency="0.75" numOctaves="4" stitchTiles="stitch" result="n"/><feColorMatrix in="n" type="saturate" values="0" result="m"/><feBlend in="SourceGraphic" in2="m" mode="soft-light"/></filter></defs></svg>);
const Glass=({level=1,children,style={},r,onClick})=>{const s=level===1?{bg:"rgba(255,255,255,0.70)",blur:"blur(20px) saturate(1.4)",bdr:"1px solid rgba(255,255,255,0.85)",sh:"0 2px 12px rgba(0,0,0,0.06), 0 1px 3px rgba(0,0,0,0.04)",rad:20}:{bg:"rgba(255,255,255,0.88)",blur:"blur(24px) saturate(1.6)",bdr:"1px solid rgba(255,255,255,0.95)",sh:"0 8px 32px rgba(0,0,0,0.10), 0 2px 8px rgba(0,0,0,0.06)",rad:28};return(<div ref={r} onClick={onClick} style={{position:"relative",overflow:"hidden",borderRadius:s.rad,background:s.bg,backdropFilter:s.blur,WebkitBackdropFilter:s.blur,border:s.bdr,boxShadow:s.sh,...style}}><div style={{position:"absolute",inset:0,borderRadius:s.rad,filter:"url(#pg)",opacity:0.035,pointerEvents:"none",zIndex:1,background:"rgba(128,128,128,0.1)"}}/><div style={{position:"absolute",top:0,left:"8%",right:"8%",height:1,background:"linear-gradient(90deg, transparent, rgba(255,255,255,0.95) 30%, white 50%, rgba(255,255,255,0.95) 70%, transparent)",zIndex:4}}/><div style={{position:"absolute",top:0,left:0,right:0,height:44,background:"linear-gradient(180deg, rgba(255,255,255,0.5), transparent)",zIndex:2,pointerEvents:"none",borderRadius:s.rad+"px "+s.rad+"px 0 0"}}/><div style={{position:"relative",zIndex:3}}>{children}</div></div>)};
const Bg=()=>(<div style={{position:"absolute",inset:0,zIndex:0}}><div style={{position:"absolute",inset:0,background:C.bg}}/><div style={{position:"absolute",inset:0,background:"linear-gradient(135deg, "+C.n100+" 0%, "+C.bg+" 50%)"}}/><div style={{position:"absolute",inset:0,background:"radial-gradient(ellipse 90% 50% at 15% 85%, rgba(190,195,210,0.35) 0%, transparent 60%)"}}/><div style={{position:"absolute",inset:0,background:"radial-gradient(ellipse 70% 40% at 85% 15%, rgba(200,205,220,0.25) 0%, transparent 55%)"}}/><div style={{position:"absolute",inset:0,filter:"url(#pg)",opacity:0.025,pointerEvents:"none",background:"rgba(128,128,128,0.08)"}}/></div>);
const Phone=({children})=>(<div style={{width:375,height:812,borderRadius:48,position:"relative",background:"#1A1A1A",padding:4}}><div style={{position:"absolute",inset:-1.5,borderRadius:50,zIndex:-1,background:"linear-gradient(160deg, #666 0%, #3a3a3a 20%, #555 40%, #333 60%, #4a4a4a 80%, #555 100%)"}}/><div style={{position:"absolute",left:-3,top:140,width:3,height:30,borderRadius:"3px 0 0 3px",background:"linear-gradient(180deg, #555, #3a3a3a)"}}/><div style={{position:"absolute",left:-3,top:200,width:3,height:54,borderRadius:"3px 0 0 3px",background:"linear-gradient(180deg, #555, #3a3a3a)"}}/><div style={{position:"absolute",left:-3,top:266,width:3,height:54,borderRadius:"3px 0 0 3px",background:"linear-gradient(180deg, #555, #3a3a3a)"}}/><div style={{position:"absolute",right:-3,top:200,width:3,height:54,borderRadius:"0 3px 3px 0",background:"linear-gradient(180deg, #555, #3a3a3a)"}}/><div style={{width:"100%",height:"100%",borderRadius:44,overflow:"hidden",position:"relative",background:C.bg}}><div style={{position:"absolute",top:11,left:"50%",transform:"translateX(-50%)",width:126,height:37,borderRadius:20,background:"#000",zIndex:100}}/>{children}</div></div>);
const Dots=({total,current})=>(<div style={{position:"absolute",bottom:32,left:"50%",transform:"translateX(-50%)",display:"flex",gap:6,zIndex:80}}>{Array.from({length:total},(_,i)=>(<div key={i} style={{width:i===current?10:6,height:i===current?10:6,borderRadius:9999,background:i===current?C.amber:C.n200,transition:"all 200ms cubic-bezier(0.34, 1.56, 0.64, 1)",boxShadow:i===current?"0 0 8px rgba(251,185,49,0.4)":"none"}}/>))}</div>);
const an=(el,kf,opts)=>{if(!el)return Promise.resolve();return el.animate(kf,{fill:"forwards",...opts}).finished};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const Beat=({children,r,visible})=>(<div ref={r} style={{position:"absolute",inset:0,zIndex:visible?5:1,visibility:visible?"visible":"hidden",opacity:0}}>{children}</div>);
const B1=()=>(<div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",padding:"68px 24px 60px"}}><div style={{fontFamily:F.b,fontWeight:500,fontSize:11,color:C.n600,letterSpacing:"0.01em",marginBottom:12}}>Kumamoto semiconductor corridor, 2024 to 2035</div><div style={{fontFamily:F.h,fontWeight:600,fontSize:26,lineHeight:1.12,color:C.n950,letterSpacing:"-0.025em"}}>{THESIS}</div></div>);
const B2=({tiles})=>(<div style={{padding:"68px 20px 60px"}}><div style={{fontFamily:F.b,fontWeight:500,fontSize:11,color:C.n600,marginBottom:14}}>Key data points</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{STATS.map((s,i)=>(<Glass key={i} level={1} r={el=>{if(tiles)tiles.current[i]=el}} style={{padding:"16px 14px",opacity:0}}><div style={{fontFamily:F.h,fontWeight:600,fontSize:28,lineHeight:1,color:C.n950,fontVariantNumeric:"tabular-nums"}}>{s.value}</div><div style={{fontFamily:F.b,fontSize:12,color:C.n800,marginTop:8}}>{s.label}</div><div style={{fontFamily:F.b,fontSize:11,color:C.n600,marginTop:2}}>{s.sub}</div></Glass>))}</div></div>);
const B3=({nodes})=>(<div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",padding:"68px 20px 60px"}}><div style={{fontFamily:F.b,fontWeight:500,fontSize:11,color:C.n600,marginBottom:14}}>Strategic timing</div><Glass level={1} style={{padding:"20px 18px"}}>{TL.map((t,i)=>(<div key={i} ref={el=>{if(nodes)nodes.current[i]=el}} style={{display:"flex",gap:14}}><div style={{display:"flex",flexDirection:"column",alignItems:"center",flexShrink:0,width:20}}><div style={{position:"relative",width:i===0?14:10,height:i===0?14:10,flexShrink:0}}><div style={{position:"absolute",inset:0,borderRadius:9999,border:"2px solid "+C.n200,opacity:0.35}}/><div className={"tl-dot-"+i} style={{position:"absolute",inset:0,borderRadius:9999,background:C.amber,transform:"scale(0)",boxShadow:"0 0 12px rgba(251,185,49,0.45)"}}/></div>{i<TL.length-1&&<div style={{width:2,flex:1,marginTop:4,position:"relative",borderRadius:1,overflow:"hidden"}}><div style={{position:"absolute",inset:0,background:C.n200,opacity:0.2}}/><div className={"tl-line-"+i} style={{position:"absolute",top:0,left:0,width:"100%",height:"100%",background:C.amber,transformOrigin:"top",transform:"scaleY(0)"}}/></div>}</div><div style={{paddingBottom:i<TL.length-1?20:0,opacity:0}} className={"tl-text-"+i}><div style={{fontFamily:F.b,fontWeight:500,fontSize:11,color:C.n600}}>{t.y}</div><div style={{fontFamily:F.h,fontWeight:600,fontSize:15,lineHeight:1.25,color:C.n950,marginTop:3}}>{t.t}</div><div style={{fontFamily:F.b,fontSize:13,lineHeight:1.55,color:C.n800,marginTop:3}}>{t.d}</div></div></div>))}</Glass></div>);
const B4=()=>(<div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",padding:"68px 20px 60px"}}><Glass level={2} style={{padding:"28px 22px"}}><div style={{fontFamily:F.h,fontWeight:600,fontSize:17,lineHeight:1.25,color:C.n950,marginBottom:10}}>Moha Intel</div><div style={{fontFamily:F.b,fontSize:14,lineHeight:1.65,color:C.n800}}>{THESIS_2}</div></Glass></div>);
const B5=({openFaq,setOpenFaq})=>(<div style={{padding:"64px 20px 56px",display:"flex",flexDirection:"column"}}><div style={{fontFamily:F.b,fontWeight:500,fontSize:11,color:C.n600,marginBottom:12}}>Risk factors</div><div style={{display:"flex",flexDirection:"column",gap:6}}>{FAQ.map((f,i)=>(<Glass key={i} level={1} onClick={e=>{e.stopPropagation();setOpenFaq(openFaq===i?-1:i)}} style={{padding:"12px 14px",cursor:"pointer"}}><div style={{display:"flex",alignItems:"flex-start",gap:8}}><div style={{flex:1}}><div style={{fontFamily:F.b,fontWeight:500,fontSize:12.5,lineHeight:1.35,color:C.n950}}>{f.q}</div><div style={{maxHeight:openFaq===i?120:0,overflow:"hidden",transition:"max-height 300ms ease, opacity 300ms ease",opacity:openFaq===i?1:0}}><div style={{fontFamily:F.b,fontSize:12,lineHeight:1.55,color:C.n800,marginTop:8}}>{f.a}</div></div></div><div style={{fontSize:14,color:C.n600,flexShrink:0,transform:openFaq===i?"rotate(180deg)":"rotate(0)",transition:"transform 300ms ease"}}>&#9662;</div></div></Glass>))}</div></div>);
const stg=async(refs,count,kf,dur,easing,delay=120)=>{for(let i=0;i<count;i++){an(refs.current[i],kf,{duration:dur,easing});if(i<count-1)await wait(delay)}await wait(dur-delay)};
const tlAnim=async(refs)=>{for(let i=0;i<4;i++){const node=refs.current[i];if(!node)continue;const dot=node.querySelector(".tl-dot-"+i);const text=node.querySelector(".tl-text-"+i);const line=node.querySelector(".tl-line-"+i);if(dot)an(dot,[{transform:"scale(0)"},{transform:"scale(1.4)"},{transform:"scale(1)"}],{duration:350,easing:E.spring});if(text)an(text,[{opacity:0,transform:"translateX(-10px)"},{opacity:1,transform:"translateX(0)"}],{duration:350,easing:E.settle});await wait(300);if(line)await an(line,[{transform:"scaleY(0)"},{transform:"scaleY(1)"}],{duration:320,easing:E.settle});await wait(40)}};
const makeVariant=(enterFn,exitFn)=>()=>{const[beat,setBeat]=useState(0);const busy=useRef(false);const b=[useRef(),useRef(),useRef(),useRef(),useRef()];const tiles=useRef([]);const nodes=useRef([]);const[oF,sOF]=useState(-1);const go=useCallback(async()=>{if(busy.current||beat>=5)return;busy.current=true;const next=beat+1;if(beat>0)await exitFn(b[beat-1].current);await wait(200);setBeat(next);await enterFn(next,b,tiles,nodes);busy.current=false},[beat]);return(<div style={{position:"relative",width:"100%",height:"100%"}} onClick={go}><Bg/><Beat r={b[0]} visible={beat===1}><B1/></Beat><Beat r={b[1]} visible={beat===2}><B2 tiles={tiles}/></Beat><Beat r={b[2]} visible={beat===3}><B3 nodes={nodes}/></Beat><Beat r={b[3]} visible={beat===4}><B4/></Beat><Beat r={b[4]} visible={beat===5}><B5 openFaq={oF} setOpenFaq={sOF}/></Beat>{beat===0&&<div style={{position:"absolute",inset:0,zIndex:90,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}><div style={{fontFamily:F.b,fontSize:13,color:C.n600,background:"rgba(255,255,255,0.7)",padding:"10px 22px",borderRadius:9999,backdropFilter:"blur(12px)",border:"1px solid rgba(255,255,255,0.85)"}}>Tap to begin</div></div>}{beat>0&&<Dots total={5} current={beat-1}/>}</div>)};

const VariantA=makeVariant(async(n,b,t,nd)=>{if(n===1)await an(b[0].current,[{opacity:0,filter:"blur(14px)",transform:"scale(1.06)"},{opacity:.4,filter:"blur(8px)",transform:"scale(1.04)"},{opacity:.8,filter:"blur(3px)",transform:"scale(1.01)"},{opacity:1,filter:"blur(0px)",transform:"scale(1)"}],{duration:1000,easing:E.settle});else if(n===2){await an(b[1].current,[{opacity:0},{opacity:1}],{duration:200,easing:E.smooth});await stg(t,6,[{opacity:0,transform:"translateY(20px) scale(0.97)"},{opacity:1,transform:"translateY(0) scale(1)"}],400,E.spring,120)}else if(n===3){await an(b[2].current,[{opacity:0},{opacity:1}],{duration:200,easing:E.smooth});await tlAnim(nd)}else if(n===4)await an(b[3].current,[{opacity:0,transform:"translateY(20px) scale(0.97)"},{opacity:1,transform:"translateY(0) scale(1)"}],{duration:450,easing:E.spring});else if(n===5)await an(b[4].current,[{opacity:0,transform:"translateY(16px)"},{opacity:1,transform:"translateY(0)"}],{duration:400,easing:E.spring})},async el=>an(el,[{opacity:1,transform:"scale(1)",filter:"blur(0px)"},{opacity:.5,transform:"scale(0.98)",filter:"blur(1px)"},{opacity:0,transform:"scale(0.96)",filter:"blur(2px)"}],{duration:300,easing:E.gentle}));

const VariantD=makeVariant(async(n,b,t,nd)=>{const pIn=[{opacity:0,transform:"perspective(1200px) translateZ(-250px) rotateX(-2deg) rotateY(1.5deg)",filter:"blur(4px)"},{opacity:.6,transform:"perspective(1200px) translateZ(-60px) rotateX(-0.5deg) rotateY(0.3deg)",filter:"blur(1px)"},{opacity:1,transform:"perspective(1200px) translateZ(0px) rotateX(0deg) rotateY(0deg)",filter:"blur(0px)"}];if(n===1)await an(b[0].current,pIn,{duration:900,easing:E.settle});else if(n===2){await an(b[1].current,pIn,{duration:800,easing:E.settle});await stg(t,6,[{opacity:0,transform:"translateZ(30px) scale(0.93)"},{opacity:1,transform:"translateZ(0) scale(1)"}],350,E.spring,100)}else if(n===3){await an(b[2].current,pIn,{duration:800,easing:E.settle});await tlAnim(nd)}else if(n===4)await an(b[3].current,pIn,{duration:800,easing:E.settle});else if(n===5)await an(b[4].current,pIn,{duration:700,easing:E.settle})},async el=>an(el,[{opacity:1,transform:"perspective(1200px) translateZ(0px) rotateX(0deg) rotateY(0deg)",filter:"blur(0px)"},{opacity:.4,transform:"perspective(1200px) translateZ(-150px) rotateX(3deg) rotateY(-2deg)",filter:"blur(2px)"},{opacity:0,transform:"perspective(1200px) translateZ(-350px) rotateX(6deg) rotateY(-3deg)",filter:"blur(4px)"}],{duration:400,easing:E.gentle}));

const VARIANTS={A:{name:"A: the crescendo",c:VariantA},D:{name:"D: the parallax",c:VariantD}};

export default function Step18RiskFactorsV8({variant}={}){
  const resolved=VARIANTS[variant]?variant:"A";
  const Cur=VARIANTS[resolved].c;
  return(
    <div style={{minHeight:"100vh",background:"#EDEEF1",display:"flex",alignItems:"center",justifyContent:"center",padding:24,fontFamily:F.b}}>
      <Noise/>
      <Phone><Cur key={resolved}/></Phone>
    </div>
  );
}
